Add forms 📝
hydaline-code/myblogapp pull request #7
Opened 2024-01-13 22:19 UTC by hydaline-code

Created a method called current_user in  ApplicationController 
Created some  forms to perform the following functions:
✔Creates a Post for  current_user 
✔Creates a comment for  current_user 
kindly ♻ 🙏

2024-01-14 00:56 UTC, VICTOR-CHUKWU requested changes
Hi @hydaline-code  👋  

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![almost](https://media.giphy.com/media/R2m2NzVxQ3pbG/giphy.gif)

## Highlights
- Good PR
- Good commit
- All linters passed
- You have implemented the greater part of this milestone

## Required Changes ♻️

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2024-01-14 00:56 UTC, VICTOR-CHUKWU commented on app/controllers/application_controller.rb
> +  end
- [ ] Kudos for adding this requirement

2024-01-14 00:56 UTC, VICTOR-CHUKWU commented on app/controllers/comments_controller.rb
> +    params.require(:comment).permit(:text)
- [ ] Impressive lines of code that meet the requirements

2024-01-14 00:56 UTC, VICTOR-CHUKWU commented on app/views/posts/new.html.erb
> +<% end %>
##Required

- [ ]  Kindly make this form to be displayed as in the wireframes. It is required to accept input for creating a post

2024-01-14 00:56 UTC, VICTOR-CHUKWU commented on app/views/comments/new.html.erb
> +<% end %>
## Required

- [ ] Kindly make this form to be displayed as in the wireframes. It is required to accept input for creating comments

2024-01-16 18:12 UTC, julie-ify reviewed
Hi @hydaline-code,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

* This is a new week and the project was not approved last week. Kindly subimt a new pull request without previous reviewer comments.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2024-01-27 02:14 UTC, merged